Style/LineLength: 
  Description: 'Limit lines to 90 characters.' 
  Max: 90
Style/StringLiterals: 
  EnforcedStyle: single_quotes 
Style/HashSyntax: 
  EnforcedStyle: hash_rockets
Style/AlignHash:
  EnforcedColonStyle: table
Lint/DefEndAlignment:
  AlignWith: start_of_line