Style/LineLength:
  Max: 90
Metrics/LineLength:
  Max: 90
Style/IfUnlessModifier:
  MaxLineLength: 90
Style/StringLiterals:
  EnforcedStyle: single_quotes
Style/HashSyntax:
  EnforcedStyle: ruby19
Style/AlignHash:
  EnforcedColonStyle: table
Lint/DefEndAlignment:
  AlignWith: start_of_line
Lint/EndAlignment:
 AlignWith: variable
Metrics/MethodLength:
  CountComments: false
  Max: 15
